global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: search-service
    static_configs:
      - targets: ['search-service:8080']
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: write-service
    static_configs:
      - targets: ['write-service:8081']
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: cron-scheduler
    static_configs:
      - targets: ['cron-scheduler:8082']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: bitmap-filter-service
    static_configs:
      - targets: ['bitmap-filter-service:50051']
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
